language: ruby
env: RACK_ENV=development
sudo: false
rvm:
- 2.3.1
services:
- docker
before_install:
- docker pull mumuki/mumuki-crystal-worker
- wget https://github.com/mumuki/mulang/releases/download/v2.2.0/mulang
- mv mulang bin/
- chmod +x bin/mulang
deploy:
  provider: rubygems
  api_key:
    secure: Eqj92sCS/K8sEEpD7SeF0461jZG6WarOUtC/RybOVXafv9ahACmFtOS7gFgqySzzRhch+753bnNxADXTqgz2BQ0GHisDsCexcIKSmmDHUorsrql/DzMWlsHt1lCfGC1JDfZqfEdcym5//8R7WJADlty78NVvomyuMn9Eo6DXmUo=
  gem: mumuki-ruby-runner
  on:
    tags: true
    repo: mumuki/mumuki-ruby-runner
